export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const FETCH_TASKS = 'FETCH_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const DEL_TASK = 'DEL_TASK'